title:
  main: "Test Paper for Trailing Slash Fix"
  short: "Test Paper"
  lead_author: "researcher"

date: "2025-08-15"

authors:
  - first_name: "Test"
    middle_name: ""
    last_name: "Author"
    position_title: "Researcher"
    affiliation:
      institution: "Test University"
      department: "Test Department"
    email: "test@example.com"

abstract: "This is a test manuscript to verify the trailing slash fix for issue #100."
