name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (e.g., v1.4.8)'
        required: true
        type: string
      dry_run:
        description: 'Perform dry run without making changes'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Set version and dry run mode
        id: config
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            VERSION="${{ github.event.client_payload.version }}"
            DRY_RUN="false"
          else
            VERSION="${{ github.event.inputs.version }}"
            DRY_RUN="${{ github.event.inputs.dry_run }}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "version_num=${VERSION#v}" >> $GITHUB_OUTPUT
          echo "dry_run=${DRY_RUN}" >> $GITHUB_OUTPUT

          if [ "$DRY_RUN" = "true" ]; then
            echo "🔍 DRY RUN MODE - No changes will be made"
          fi

      - name: Download template update script
        run: |
          # Get the script from the main repository
          curl -sLO https://raw.githubusercontent.com/henriqueslab/rxiv-maker/main/scripts/update-package-templates.py
          curl -sLO https://raw.githubusercontent.com/henriqueslab/rxiv-maker/main/scripts/validate-package-templates.py
          chmod +x update-package-templates.py validate-package-templates.py

      - name: Download formula template
        run: |
          # Get the template from the main repository
          curl -sLO https://raw.githubusercontent.com/henriqueslab/rxiv-maker/main/submodules/homebrew-rxiv-maker/Formula/rxiv-maker.rb.template
          mv rxiv-maker.rb.template Formula/rxiv-maker.rb.template

      - name: Validate template
        run: |
          echo "🔍 Validating formula template..."
          python validate-package-templates.py validate-templates

      - name: Backup current formula
        if: steps.config.outputs.dry_run != 'true'
        run: |
          cp Formula/rxiv-maker.rb Formula/rxiv-maker.rb.backup
          echo "✅ Backed up current formula"

      - name: Update formula from template
        id: update
        run: |
          VERSION="${{ steps.config.outputs.version }}"
          DRY_RUN_FLAG=""

          if [ "${{ steps.config.outputs.dry_run }}" = "true" ]; then
            DRY_RUN_FLAG="--dry-run"
          fi

          python update-package-templates.py homebrew "$VERSION" $DRY_RUN_FLAG

      - name: Validate updated formula
        if: steps.config.outputs.dry_run != 'true'
        run: |
          echo "🔍 Validating updated formula..."

          # Check Ruby syntax
          if command -v ruby >/dev/null 2>&1; then
            ruby -c Formula/rxiv-maker.rb
            echo "✅ Ruby syntax validation passed"
          else
            echo "⚠️  Ruby not available for syntax validation"
          fi

          # Show key changes
          echo "📋 Formula changes:"
          if [ -f Formula/rxiv-maker.rb.backup ]; then
            echo "Version and URL updates:"
            diff Formula/rxiv-maker.rb.backup Formula/rxiv-maker.rb | grep -E '^[<>].*releases/download|^[<>].*sha256' || echo "No URL/hash changes detected"
          fi

      - name: Test formula (basic check)
        if: steps.config.outputs.dry_run != 'true'
        run: |
          echo "🧪 Testing formula structure..."

          # Check that all placeholders were replaced
          if grep -q "{{.*}}" Formula/rxiv-maker.rb; then
            echo "❌ Unreplaced placeholders found:"
            grep "{{.*}}" Formula/rxiv-maker.rb
            exit 1
          fi

          # Check that version is present
          VERSION="${{ steps.config.outputs.version }}"
          if ! grep -q "$VERSION" Formula/rxiv-maker.rb; then
            echo "❌ Version $VERSION not found in formula"
            exit 1
          fi

          echo "✅ Formula structure validation passed"

      - name: Commit and push changes
        if: steps.config.outputs.dry_run != 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if there are any changes
          if git diff --quiet Formula/rxiv-maker.rb; then
            echo "ℹ️  No changes to commit"
            echo "status=no-changes" >> $GITHUB_OUTPUT
          else
            # Stage and commit changes
            git add Formula/rxiv-maker.rb
            git commit -m "Update rxiv-maker to ${{ steps.config.outputs.version }}

            🤖 Automated update using template system

            - Updated version to ${{ steps.config.outputs.version }}
            - Updated binary URLs and checksums
            - Validated formula syntax and structure"

            git push
            echo "✅ Formula updated and pushed"
            echo "status=updated" >> $GITHUB_OUTPUT
          fi

      - name: Create detailed summary
        run: |
          VERSION="${{ steps.config.outputs.version }}"
          DRY_RUN="${{ steps.config.outputs.dry_run }}"

          echo "## 🍺 Homebrew Formula Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: $VERSION" >> $GITHUB_STEP_SUMMARY
          echo "- **Dry Run**: $DRY_RUN" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "$DRY_RUN" = "true" ]; then
            echo "### 🔍 Dry Run Results" >> $GITHUB_STEP_SUMMARY
            echo "This was a dry run - no changes were made to the repository." >> $GITHUB_STEP_SUMMARY
          else
            echo "### 📋 Changes Made" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Formula updated from template" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Binary URLs updated to $VERSION" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ SHA256 checksums calculated and updated" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Ruby syntax validated" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Formula structure validated" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔗 Installation" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo 'brew tap henriqueslab/rxiv-maker' >> $GITHUB_STEP_SUMMARY
          echo 'brew install rxiv-maker' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Handle errors and rollback
        if: failure() && steps.config.outputs.dry_run != 'true'
        run: |
          echo "❌ Formula update failed - attempting rollback"

          if [ -f Formula/rxiv-maker.rb.backup ]; then
            cp Formula/rxiv-maker.rb.backup Formula/rxiv-maker.rb
            echo "✅ Rolled back to previous formula version"

            # Check if we need to commit the rollback
            if ! git diff --quiet Formula/rxiv-maker.rb; then
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add Formula/rxiv-maker.rb
              git commit -m "Rollback formula update due to validation failure"
              git push
              echo "✅ Rollback committed and pushed"
            fi
          else
            echo "⚠️  No backup found - manual intervention may be required"
          fi

          echo "## ❌ Formula Update Failed" >> $GITHUB_STEP_SUMMARY
          echo "The formula update failed and has been rolled back if possible." >> $GITHUB_STEP_SUMMARY
          echo "Please check the logs for details and manual intervention may be required." >> $GITHUB_STEP_SUMMARY
