name: Build Base Images

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'images/base/**'
      - '.github/workflows/build-base.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'images/base/**'
      - '.github/workflows/build-base.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the built image'
        required: false
        default: 'latest'
      platforms:
        description: 'Platforms to build for'
        required: false
        default: 'linux/amd64,linux/arm64'

env:
  REGISTRY: docker.io
  BASE_IMAGE_NAME: henriqueslab/rxiv-maker-base

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PUSH }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{ github.event.inputs.tag }},enable=${{ github.event.inputs.tag != '' }}

    - name: Build and push base image
      uses: docker/build-push-action@v5
      with:
        context: ./images/base
        platforms: ${{ github.event.inputs.platforms || 'linux/amd64,linux/arm64' }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Test base image functionality
      if: github.event_name == 'pull_request'
      run: |
        # Load image for testing (only for PRs)
        docker build -t test-base ./images/base

        # Test basic functionality
        echo "Testing Python..."
        docker run --rm test-base python3 --version

        echo "Testing LaTeX..."
        docker run --rm test-base pdflatex --version

        echo "Testing Node.js..."
        docker run --rm test-base node --version

        echo "Testing Mermaid..."
        docker run --rm test-base mmdc --version

        echo "Testing R..."
        docker run --rm test-base R --version

        echo "All tests passed!"

    - name: Update repository description
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      run: |
        # Update Docker Hub repository description
        curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.DOCKER_PUSH }}" \
          -H "Content-Type: application/json" \
          -d '{
            "full_description": "# Rxiv-Maker Base Docker Image\n\nUbuntu-based image with LaTeX, Python, Node.js, R, and Mermaid CLI pre-installed for scientific document generation.\n\n## Quick Start\n```bash\ndocker run -it --rm -v $(pwd):/workspace henriqueslab/rxiv-maker-base:latest\n```\n\n## Features\n- Complete LaTeX distribution\n- Python 3.11 with scientific libraries\n- Node.js 18 with Mermaid CLI\n- R with common packages\n- Multi-platform support (AMD64/ARM64)\n\n## Documentation\nSee [GitHub repository](https://github.com/HenriquesLab/docker-rxiv-maker) for full documentation."
          }' \
          "https://hub.docker.com/v2/repositories/${{ env.BASE_IMAGE_NAME }}/" || true

    - name: Summary
      if: github.event_name != 'pull_request'
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: ${{ env.BASE_IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Tags**: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Platforms**: ${{ github.event.inputs.platforms || 'linux/amd64,linux/arm64' }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Status**: ✅ Successfully built and pushed" >> $GITHUB_STEP_SUMMARY
