[files]
# Ignore certain files that might contain intentional "typos"
extend-exclude = [
    "*.log",
    "*.bib",
    "*.tex",
    "*.pdf",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.svg",
    "build/",
    "dist/",
    ".git/",
    "__pycache__/",
    "*.egg-info/",
]

[default]
# Accept common technical abbreviations and names
extend-ignore-re = [
    # LaTeX commands and environments
    "\\\\[a-zA-Z]+",
    # File paths and URLs
    "[a-zA-Z0-9-_.]+\\.[a-zA-Z0-9]{2,}",
]

[default.extend-words]
# Add technical terms and proper names that might be flagged as typos
rxiv = "rxiv"
arxiv = "arxiv"
biorxiv = "biorxiv"
preprint = "preprint"
doi = "doi"
orcid = "orcid"
yaml = "yaml"
toml = "toml"
# Institution names and proper nouns
instituto = "instituto"  # Portuguese for "institute"
tennant = "tennant"      # Proper surname
# LaTeX formatting sequences
ois = "ois"              # Part of LaTeX accent commands like {\c{c}}ois
# File extensions
fot = "fot"              # LaTeX font outline file extension
