# Article Forge Configuration
# Project settings for automated LaTeX article building

# Project Information
project:
  name: "article-forge"
  title: "Your Article Title Here"
  version: "1.0.0"
  
# Authors
authors:
  - name: "Author Name"
    affiliations: ["1", "2"]
    email: "author@institution.edu"
  - name: "Second Author" 
    affiliations: ["1"]
    email: "second@institution.edu"

# Affiliations
affiliations:
  "1": "Department of Research, University Name"
  "2": "Institute of Advanced Studies"

# Build Configuration
build:
  main_file: "main.tex"
  output_name: "main.pdf"
  compiler: "pdflatex"
  bibliography: true
  bibtex_compiler: "bibtex"
  
# Paths
paths:
  tex_dir: "src/tex"
  bib_dir: "src/bibliography"
  fig_dir: "src/figures"
  data_dir: "src/data"
  build_dir: "build"
  output_dir: "build/output"
  
# GitHub Actions
github:
  build_on_push: true
  build_on_pr: true
  auto_release: true
  artifact_retention_days: 30
  
# Docker
docker:
  image: "texlive/texlive:latest"
  enable_watch: true
  
# Development
development:
  watch_mode: true
  quick_build: false
  clean_build: true
