# Figure Generation Configuration for Article-Forge

# Global settings
figure_generation:
  # Output settings
  output_directory: "src/figures"
  formats:
    - pdf      # Primary format for LaTeX
    - png      # Backup raster format
  
  # Quality settings
  dpi: 300
  bbox_inches: "tight"
  pad_inches: 0.1

# Matplotlib configuration
matplotlib:
  # LaTeX integration
  use_latex: true
  use_pgf: false  # Set to true for maximum LaTeX integration
  
  # Font settings
  font_family: "serif"
  font_serif: "Computer Modern"
  font_size: 10
  
  # Figure dimensions (inches)
  figure_sizes:
    single_column: [3.5, 2.6]
    double_column: [7.0, 5.25]
    square: [4, 4]
    wide: [8, 3]
    tall: [4, 6]
  
  # LaTeX preamble
  latex_preamble: |
    \usepackage{amsmath}
    \usepackage{amssymb}
    \usepackage{siunitx}
  
  # Color scheme
  colors:
    primary: "#1f77b4"
    secondary: "#ff7f0e"
    accent: "#2ca02c"
    error: "#d62728"
    warning: "#ff8c00"
    info: "#17a2b8"
    success: "#28a745"
    muted: "#6c757d"

# Seaborn configuration
seaborn:
  style: "whitegrid"
  palette: "deep"
  
  # Custom palettes
  custom_palettes:
    publication: ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"]
    grayscale: ["#000000", "#404040", "#808080", "#b0b0b0", "#d0d0d0"]
    scientific: ["#0173b2", "#de8f05", "#029e73", "#cc78bc", "#ca9161"]
    colorblind: ["#0072B2", "#E69F00", "#009E73", "#F0E442", "#CC79A7"]

# Mermaid configuration
mermaid:
  # CLI settings
  cli_command: "mmdc"
  default_width: 800
  default_height: 600
  
  # Theme configuration
  theme_config:
    theme: "base"
    themeVariables:
      primaryColor: "#ffffff"
      primaryTextColor: "#000000"
      primaryBorderColor: "#000000"
      lineColor: "#000000"
      secondaryColor: "#f5f5f5"
      tertiaryColor: "#e0e0e0"
      fontFamily: "Times, serif"
      fontSize: "12px"
  
  # Diagram-specific settings
  flowchart:
    nodeSpacing: 50
    rankSpacing: 50
    curve: "basis"

# Figure-specific configurations
figures:
  Figure1:
    type: "matplotlib"
    description: "Sample data visualization"
    size: "single_column"
    
  Figure2:
    type: "seaborn"
    description: "Statistical analysis"
    size: "double_column"
    
  methodology_diagram:
    type: "mermaid"
    description: "Research methodology flowchart"
    template: "methodology_template.mmd"
    
  system_architecture:
    type: "mermaid"
    description: "System architecture diagram"
    template: "architecture_template.mmd"

# Dependencies
dependencies:
  python_packages:
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - numpy>=1.24.0
    - pandas>=2.0.0
    - scipy>=1.10.0
    - Pillow>=9.0.0
    - pypdf>=3.0.0
  
  external_tools:
    - name: "Mermaid CLI"
      command: "mmdc"
      install_command: "npm install -g @mermaid-js/mermaid-cli"
      check_command: "mmdc --version"
