# Article-Forge Docker Compose - Optimized Configuration
# Provides multiple services for different use cases with efficient resource usage

services:
  # =====================================
  # Production Service - PDF Generation
  # =====================================
  article-forge:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile
      target: production
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: article-forge:latest
    container_name: article-forge-prod
    volumes:
      # Mount only necessary directories for production
      - ../../:/app:ro  # Read-only for security
      - ../../output:/app/output:rw  # Read-write for output
      - article-forge-cache:/tmp  # Temporary cache volume
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src/py
      - PYTHONUNBUFFERED=1
    networks:
      - rxiv-forge-net
    restart: "no"
    # Resource limits for efficiency
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # =====================================
  # Development Service - Interactive
  # =====================================
  dev:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile
      target: development
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: rxiv-forge:dev
    container_name: rxiv-forge-dev
    volumes:
      # Full read-write access for development
      - ../../:/app:rw
      - rxiv-forge-cache:/tmp
      - dev-home:/home/appuser  # Persistent dev environment
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src/py
      - PYTHONUNBUFFERED=1
      - DEVELOPMENT=1
    networks:
      - rxiv-forge-net
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    # Development resource limits
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4.0'

  # =====================================
  # Watch Service - Auto-rebuild
  # =====================================
  watch:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile
      target: development
    image: rxiv-forge:dev
    container_name: rxiv-forge-watch
    volumes:
      - ../../:/app:rw
      - rxiv-forge-cache:/tmp
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src/py
      - PYTHONUNBUFFERED=1
    networks:
      - rxiv-forge-net
    command: make watch
    restart: unless-stopped

  # =====================================
  # Test Service - CI/CD Testing
  # =====================================
  test:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile
      target: development
    image: rxiv-forge:dev
    container_name: rxiv-forge-test
    volumes:
      - ../../:/app:ro
      - rxiv-forge-cache:/tmp
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src/py
      - PYTHONUNBUFFERED=1
    networks:
      - rxiv-forge-net
    command: make test
    profiles:
      - testing

# =====================================
# Networks and Volumes
# =====================================
networks:
  rxiv-forge-net:
    driver: bridge
    name: rxiv-forge-network

volumes:
  rxiv-forge-cache:
    name: rxiv-forge-cache
    driver: local
  dev-home:
    name: rxiv-forge-dev-home
    driver: local
