# Manuscript Configuration
title: "My Research Paper"
# subtitle: "Optional subtitle"
authors:
  - name: "Your Name"
    email: "your.email@example.com"
    affiliations: [1]
    orcid: ""  # Optional ORCID ID

affiliations:
  - id: 1
    name: "Your Institution"
    department: ""
    city: ""
    country: ""

# Publication metadata
date: "2025-08-15"                      # Publication date (YYYY-MM-DD format)
status: "draft"                         # Status: draft, submitted, accepted, published
use_line_numbers: true                  # Enable line numbers for manuscript review
license: "CC BY 4.0"                    # Creative Commons license (CC BY 4.0, CC BY-SA 4.0, etc.)
acknowledge_rxiv_maker: true            # Include Rxiv-Maker acknowledgement and citation
enable_doi_validation: true             # Enable DOI validation against CrossRef/DataCite APIs

# Keywords and abstract
keywords: ["keyword1", "keyword2", "keyword3"]
abstract: |
  This is the abstract of your manuscript. Replace this text with your actual abstract.

  You can use multiple paragraphs here. The abstract should be concise and informative.

# Bibliography settings
bibliography_style: "rxiv_maker_style"  # or "nature", "science", "ieee", etc.
citation_style: "nature"  # or "apa", "mla", etc.

# Figure settings
figure_format: "png"  # or "pdf", "svg"
figure_dpi: 300

# Build settings
latex_engine: "pdflatex"  # or "xelatex", "lualatex"
