name: Build and Release PDF

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      manuscript_path:
        description: 'Path to manuscript directory'
        required: false
        default: 'MANUSCRIPT'
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      manuscript_path: ${{ steps.set-path.outputs.manuscript_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set manuscript path
        id: set-path
        run: |
          # Load environment variables from .env file if it exists
          if [ -f ".env" ]; then
            set -a
            source .env
            set +a
          fi

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            MANUSCRIPT_PATH="${{ github.event.inputs.manuscript_path }}"
          else
            # Use the value from .env file or fallback to EXAMPLE_MANUSCRIPT
            MANUSCRIPT_PATH="${MANUSCRIPT_PATH:-EXAMPLE_MANUSCRIPT}"
          fi

          echo "Using manuscript path: $MANUSCRIPT_PATH"
          echo "manuscript_path=$MANUSCRIPT_PATH" >> $GITHUB_OUTPUT

  build-pdf:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4



    - name: Set manuscript path from prepare job
      run: |
        echo "MANUSCRIPT_PATH=${{ needs.prepare.outputs.manuscript_path }}" >> $GITHUB_ENV
        echo "Using manuscript path: ${{ needs.prepare.outputs.manuscript_path }}"

    # Install LaTeX and Python dependencies directly
    - name: Install dependencies
      run: |
        echo "Installing TeXLive and Python dependencies directly..."

        # Update and install LaTeX packages
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          texlive-latex-base \
          texlive-latex-recommended \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-fonts-extra \
          texlive-science \
          texlive-bibtex-extra \
          texlive-pictures \
          biber \
          python3 \
          python3-pip \
          python3-venv \
          make \
          curl

        # Install Python dependencies
        python3 -m pip install --upgrade pip
        python3 -m pip install \
          pyyaml \
          matplotlib \
          pandas \
          seaborn \
          pypdf \
          python-dotenv



    # Cache LaTeX build outputs from previous runs
    - name: Cache LaTeX outputs
      uses: actions/cache@v4
      with:
        path: |
          output/*.aux
          output/*.bbl
          output/*.blg
          output/*.toc
          output/*.out
        key: ${{ runner.os }}-latex-${{ hashFiles('${{ needs.prepare.outputs.manuscript_path }}/**/*.md', '${{ needs.prepare.outputs.manuscript_path }}/**/*.bib', '${{ needs.prepare.outputs.manuscript_path }}/**/*.yml') }}
        restore-keys: |
          ${{ runner.os }}-latex-

    # Cache processed figures
    - name: Cache processed figures
      uses: actions/cache@v4
      with:
        path: |
          ${{ needs.prepare.outputs.manuscript_path }}/FIGURES/*/
          cache/figures
        key: ${{ runner.os }}-figures-${{ hashFiles('${{ needs.prepare.outputs.manuscript_path }}/FIGURES/**/*') }}
        restore-keys: |
          ${{ runner.os }}-figures-

    - name: Generate PDF
      run: |
        echo "✅ Running PDF generation natively (no Docker)"

        # Set up environment
        export MANUSCRIPT_PATH=${{ needs.prepare.outputs.manuscript_path }}
        export TEXMFVAR=/tmp/texmf-var
        export FORCE_FIGURES=false

        # Create necessary directories
        mkdir -p /tmp/texmf-var output

        # Run the build directly
        make _build_pdf

    - name: Check PDF generation
      run: |
        echo "Checking output directory contents..."
        ls -la output/ || echo "Output directory not found"

        if [ -f "output/MANUSCRIPT.pdf" ]; then
          echo "✅ PDF generated successfully"
          ls -la output/MANUSCRIPT.pdf
          file output/MANUSCRIPT.pdf
        else
          echo "❌ ERROR: PDF not found in output directory"
          echo "Contents of output directory:"
          find output/ -type f 2>/dev/null || echo "No files found in output/"

          echo "Checking for LaTeX log files:"
          find output/ -name "*.log" -exec echo "=== {} ===" \; -exec tail -50 {} \; 2>/dev/null || echo "No log files found"
          exit 1
        fi

    - name: Prepare release assets
      id: prepare-release
      run: |
        # Create release directory
        mkdir -p release

        # Copy PDF with descriptive name
        MANUSCRIPT_DIR="${{ needs.prepare.outputs.manuscript_path }}"
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9]/_/g')

        # Use the existing PDF if it has a custom name, otherwise use generic name
        if [ -f "${MANUSCRIPT_DIR}"/*.pdf ]; then
          PDF_NAME=$(ls "${MANUSCRIPT_DIR}"/*.pdf | head -1 | xargs basename)
          cp "${MANUSCRIPT_DIR}/${PDF_NAME}" "release/${PDF_NAME}"
        else
          PDF_NAME="manuscript_${BRANCH_NAME}_${TIMESTAMP}.pdf"
          cp "output/MANUSCRIPT.pdf" "release/${PDF_NAME}"
        fi

        # Set output for later steps
        echo "PDF_NAME=${PDF_NAME}" >> $GITHUB_OUTPUT
        echo "PDF_FILENAME=${PDF_NAME}" >> $GITHUB_ENV

        # Create build info
        cat > release/build_info.txt << EOF
        Build Information:
        - Repository: ${{ github.repository }}
        - Branch: ${{ github.ref_name }}
        - Commit: ${{ github.sha }}
        - Manuscript Path: ${{ needs.prepare.outputs.manuscript_path }}
        - Build Date: $(date)
        - Workflow: ${{ github.workflow }}
        - Run ID: ${{ github.run_id }}
        EOF

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-pdf
        path: |
          release/*.pdf
          release/build_info.txt
        retention-days: 90

    - name: Determine most recent tag (starting with v) and release existence
      id: tag-check
      run: |
        # List all tags starting with 'v', pick the most recent one (sorted by version)
        MOST_RECENT_TAG=$(git tag --list 'v*' --sort=-v:refname | head -n 1)
        echo "Most recent tag: $MOST_RECENT_TAG"
        echo "most_recent_tag=$MOST_RECENT_TAG" >> $GITHUB_OUTPUT

        # Check if a release exists for the most recent tag
        if [ -n "$MOST_RECENT_TAG" ]; then
          RELEASE_JSON=$(gh release view "$MOST_RECENT_TAG" --json tagName --jq '.tagName' 2>/dev/null || echo "")
          if [ "$RELEASE_JSON" = "$MOST_RECENT_TAG" ]; then
            echo "release_exists=true" >> $GITHUB_OUTPUT
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "release_exists=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release for most recent tag if missing
      if: steps.tag-check.outputs.most_recent_tag != '' && steps.tag-check.outputs.release_exists == 'false'
      run: |
        gh release create "${{ steps.tag-check.outputs.most_recent_tag }}" \
          release/*.pdf \
          release/build_info.txt \
          --title "Release ${{ steps.tag-check.outputs.most_recent_tag }}" \
          --notes "## 📄 PDF Build for Tag \`${{ steps.tag-check.outputs.most_recent_tag }}\`\nThis release was automatically created for the most recent tag."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Create or update latest-pdf release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     tag_name: latest-pdf
    #     name: "Latest PDF Build"
    #     body: |
    #       ## 📄 Latest PDF Build

    #       **Manuscript:** `${{ needs.prepare.outputs.manuscript_path }}`
    #       **Branch:** `${{ github.ref_name }}`
    #       **Commit:** `${{ github.sha }}`
    #       **Build Date:** $(date)

    #       ### 📥 Download Links
    #       - **PDF:** [${{ steps.prepare-release.outputs.PDF_NAME }}](https://github.com/${{ github.repository }}/releases/download/latest-pdf/${{ steps.prepare-release.outputs.PDF_NAME }})
    #       - **Build Info:** [build_info.txt](https://github.com/${{ github.repository }}/releases/download/latest-pdf/build_info.txt)

    #       ### 🔗 Direct Download URL
    #       ```
    #       https://github.com/${{ github.repository }}/releases/latest/download/${{ steps.prepare-release.outputs.PDF_NAME }}
    #       ```

    #       ---
    #       *This release is automatically updated when a tagged commit is pushed or when the action is manually triggered.*
    #     files: |
    #       release/*.pdf
    #       release/build_info.txt
    #     files: |
    #       release/*.pdf
    #       release/build_info.txt
