name: Docker Build Debug

on:
  push:
    branches: [dev]
    paths:
      - '.github/workflows/docker-debug.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  detect-changes:
    name: Detect Changes (Debug)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      should-build: ${{ steps.decision.outputs.should-build }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Simple change detection
        run: |
          echo "Testing simple change detection..."

          # Basic file listing
          echo "Files in current directory:"
          ls -la | head -10

          # Test git functionality
          echo "Git status:"
          git status --porcelain || echo "No git status changes"

          echo "Git log (last 2):"
          git log --oneline -2 || echo "Git log failed"

          echo "✅ Simple detection completed"

      - name: Build decision (debug)
        id: decision
        run: |
          echo "Making simple build decision..."
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"

          # Always build for this debug workflow
          echo "should-build=true" >> $GITHUB_OUTPUT
          echo "🚀 Debug mode - will always build"
