name: Docker Build & Release

on:
  push:
    branches: [main, dev]
    paths:
      - 'src/docker/images/base/Dockerfile'
      - 'pyproject.toml'
      - 'src/docker/images/base/build.sh'
      - 'src/docker/images/base/Makefile'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'tests/**'

  pull_request:
    branches: [main, dev]
    paths:
      - 'src/docker/images/base/Dockerfile'
      - 'pyproject.toml'
      - 'src/docker/images/base/build.sh'
      - 'src/docker/images/base/Makefile'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'tests/**'

  release:
    types: [published]

  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build for'
        required: false
        default: 'linux/amd64,linux/arm64'
        type: string
      push_to_registry:
        description: 'Push to Docker Hub'
        required: false
        default: false
        type: boolean
      test_only:
        description: 'Build and test only (no push)'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1
  DOCKER_BUILDKIT: 1
  REGISTRY: docker.io
  IMAGE_NAME: henriqueslab/rxiv-maker-base

jobs:
  # Simplified change detection
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      should-build: ${{ steps.decision.outputs.should-build }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect file changes
        id: changes
        run: |
          echo "Checking for relevant file changes..."

          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          else
            echo "⚠️ Initial commit detected"
            CHANGED_FILES=$(git show --name-only --pretty=format: HEAD)
          fi

          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Check for Dockerfile changes
          if echo "$CHANGED_FILES" | grep -E '^src/docker/images/base/Dockerfile$'; then
            echo "dockerfile=true" >> $GITHUB_OUTPUT
            echo "📝 Dockerfile changed"
          else
            echo "dockerfile=false" >> $GITHUB_OUTPUT
          fi

          # Check for dependency changes
          if echo "$CHANGED_FILES" | grep -E '^pyproject.toml$'; then
            echo "dependencies=true" >> $GITHUB_OUTPUT
            echo "📦 Dependencies changed"
          else
            echo "dependencies=false" >> $GITHUB_OUTPUT
          fi

          # Check for build script changes
          if echo "$CHANGED_FILES" | grep -E '^src/docker/images/base/(build\.sh|Makefile)$'; then
            echo "build-scripts=true" >> $GITHUB_OUTPUT
            echo "🔧 Build scripts changed"
          else
            echo "build-scripts=false" >> $GITHUB_OUTPUT
          fi

      - name: Build decision
        id: decision
        run: |
          # Simple build decision logic
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "should-build=true" >> $GITHUB_OUTPUT
            echo "🚀 Manual trigger - will build"
          elif [ "${{ github.event_name }}" == "release" ]; then
            echo "should-build=true" >> $GITHUB_OUTPUT
            echo "🏷️ Release trigger - will build"
          elif [ "${{ steps.changes.outputs.dockerfile }}" == "true" ] || \
               [ "${{ steps.changes.outputs.dependencies }}" == "true" ] || \
               [ "${{ steps.changes.outputs.build-scripts }}" == "true" ]; then
            echo "should-build=true" >> $GITHUB_OUTPUT
            echo "📋 Relevant changes detected - will build"
          else
            echo "should-build=false" >> $GITHUB_OUTPUT
            echo "⏭️ No relevant changes - skipping build"
          fi

  # Build and test Docker image
  build-and-test:
    name: Build & Test Docker Image
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.should-build == 'true'
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set platform slug
        id: platform
        run: |
          PLATFORM_SLUG=$(echo "${{ matrix.platform }}" | sed 's/\//-/g')
          echo "slug=$PLATFORM_SLUG" >> $GITHUB_OUTPUT
          echo "Platform: ${{ matrix.platform }} -> Slug: $PLATFORM_SLUG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        timeout-minutes: 45
        with:
          context: .
          file: src/docker/images/base/Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=build-${{ matrix.platform }}
          cache-to: type=gha,scope=build-${{ matrix.platform }},mode=max
          outputs: type=docker,dest=/tmp/image-${{ steps.platform.outputs.slug }}.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ steps.platform.outputs.slug }}
          path: /tmp/image-${{ steps.platform.outputs.slug }}.tar
          retention-days: 1

  # Test the built images
  test-images:
    name: Test Docker Images
    runs-on: ubuntu-latest
    needs: [detect-changes, build-and-test]
    if: needs.detect-changes.outputs.should-build == 'true'
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download image artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: docker-image-*
          merge-multiple: true

      - name: Load Docker images
        run: |
          # Load all built images
          for image_file in docker-image-*.tar; do
            if [ -f "$image_file" ]; then
              echo "Loading $image_file..."
              docker load --input "$image_file"
            fi
          done

          # List loaded images
          docker images | grep henriqueslab/rxiv-maker-base || echo "No images found"

          # Ensure a :latest tag exists for tests
          if ! docker images --format '{{.Repository}}:{{.Tag}}' | grep -q '^henriqueslab/rxiv-maker-base:latest$'; then
            most_recent=$(docker images --format '{{.Repository}}:{{.Tag}}' | awk '/^henriqueslab\/rxiv-maker-base:/ {print; exit}')
            if [ -n "$most_recent" ]; then
              echo "Tagging $most_recent as henriqueslab/rxiv-maker-base:latest for tests"
              docker tag "$most_recent" henriqueslab/rxiv-maker-base:latest
            fi
          fi

      - name: Test Docker image
        run: |
          echo "🧪 Testing built Docker image..."
          docker run --rm henriqueslab/rxiv-maker-base:latest python3 -c "
          import sys
          print(f'Python version: {sys.version}')
          print('✅ Docker image test successful!')
          "

  # Push to Docker Hub (only on main branch or releases)
  push-to-registry:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: [detect-changes, build-and-test, test-images]
    if: |
      needs.detect-changes.outputs.should-build == 'true' &&
      (
        github.ref == 'refs/heads/main' ||
        github.event_name == 'release' ||
        (github.event_name == 'workflow_dispatch' && github.event.inputs.push_to_registry == 'true')
      ) &&
      github.event.inputs.test_only != 'true'
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/docker/images/base/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=build-linux/amd64
          cache-to: type=gha,scope=build-linux/amd64,mode=max
