name: Create Release with PDF

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate LaTeX from Markdown
      run: |
        python src/tex/py/generate_article.py --output-dir output
        
    - name: Build LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ARTICLE.tex
        working_directory: output
        compiler: pdflatex
        args: -shell-escape -interaction=nonstopmode -file-line-error
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: output/ARTICLE.pdf
        body: |
          ## Automated Release
          
          This release contains the automatically compiled PDF of the article.
          
          ### Changes
          - Built from commit ${{ github.sha }}
          - Compiled on ${{ github.run_id }}
          
          ### Features
          - Dynamic author information with social media integration
          - Generated from YAML metadata in 00_ARTICLE.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
