name: Test APT Minimal

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  test-validation:
    name: Test APT Scripts Exist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate APT scripts exist
        run: |
          echo "Checking APT script files..."

          scripts=(
            "packaging/scripts/test-apt-container.sh"
            "packaging/scripts/run-container-tests.sh"
            "packaging/scripts/validate-apt-repo.sh"
            "packaging/scripts/build-deb.sh"
            "packaging/scripts/setup-apt-repo.sh"
          )

          for script in "${scripts[@]}"; do
            if [[ -f "$script" ]]; then
              echo "✅ Found: $script"
            else
              echo "❌ Missing: $script"
              exit 1
            fi
          done

          echo "✅ All APT scripts found successfully!"
